import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But we want to create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Module 1 - ROS 2 Nervous System',
      items: [
        'module-1-ros2-nervous-system/ros2-fundamentals',
        'module-1-ros2-nervous-system/python-agents-with-rclpy',
        'module-1-ros2-nervous-system/humanoid-robot-description-urdf',
      ],
    },
    {
      type: 'category',
      label: 'Module 2 - The Digital Twin',
      items: [
        'module-2/digital-twins',
        'module-2/unity-visualization',
      ],
    },
    {
      type: 'category',
      label: 'Module 3 - The AI-Robot Brain (NVIDIA Isaac)',
      items: [
        'module-3-ai-robot-brain/isaac-overview',
        'module-3-ai-robot-brain/isaac-sim',
        'module-3-ai-robot-brain/isaac-ros',
        'module-3-ai-robot-brain/nav2-humanoids',
      ],
    },
    {
      type: 'category',
      label: 'Module 4 - Vision-Language-Action (VLA)',
      items: [
        'module-4-vla/vla-overview',
        'module-4-vla/voice-to-action',
        'module-4-vla/llm-task-planning',
        'module-4-vla/autonomous-pipeline',
      ],
    },
  ],
};

export default sidebars;