"""
Main entry point for the RAG Agent API
Handles the flow: Query → retrieve → agent → response
"""
import os
import logging
from fastapi import FastAPI, HTTPException, BackgroundTasks
from pydantic import BaseModel
from typing import Optional, List
import cohere
from qdrant_client import QdrantClient
from dotenv import load_dotenv


# Load environment variables
load_dotenv()

# Set up logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Initialize clients
cohere_api_key = os.getenv("COHERE_API_KEY")
qdrant_url = os.getenv("QDRANT_URL")
qdrant_api_key = os.getenv("QDRANT_API_KEY")

if not cohere_api_key:
    raise ValueError("COHERE_API_KEY environment variable is required")
if not qdrant_url:
    raise ValueError("QDRANT_URL environment variable is required")
if not qdrant_api_key:
    raise ValueError("QDRANT_API_KEY environment variable is required")

co = cohere.Client(cohere_api_key)
qdrant_client = QdrantClient(url=qdrant_url, api_key=qdrant_api_key)

# Initialize FastAPI app
app = FastAPI(
    title="RAG Agent API",
    description="API for RAG agent that provides context-grounded answers based on textbook content",
    version="1.0.0"
)


class QueryRequest(BaseModel):
    query: str
    selected_text: Optional[str] = None
    session_id: Optional[str] = None
    include_citations: Optional[bool] = True


class Citation(BaseModel):
    url: str
    section_title: str
    confidence: float
    text_excerpt: str


class QueryResponse(BaseModel):
    id: str
    query_id: str
    answer: str
    citations: List[Citation]
    sources: List[str]
    confidence_score: float
    response_time_ms: int
    session_id: Optional[str] = None


@app.get("/")
def read_root():
    return {"message": "RAG Agent API is running"}


@app.post("/query", response_model=QueryResponse)
async def process_query(request: QueryRequest):
    """
    Process a query through the RAG pipeline:
    1. (In a full implementation) retrieve relevant content from the knowledge base
    2. Generate a context-grounded response using the agent
    3. Format and return the response with citations
    """
    logger.info(f"Processing query: {request.query[:50]}...")
    
    # In a full implementation, this would:
    # 1. Use the retrieval system to find relevant content
    # 2. Generate embeddings for the query
    # 3. Use the Cohere agent to generate a response based on retrieved content
    # 4. Format the response with citations
    
    # For now, returning a mock response
    # In a real implementation, we would connect to the retrieval system and Cohere agent
    mock_answer = f"This is a mock response to your query: '{request.query}'. In a full implementation, this would be generated by the RAG agent based on the textbook content."
    
    # Create mock citations
    citations = [
        Citation(
            url="https://example.com/textbook-section",
            section_title="Example Section Title",
            confidence=0.85,
            text_excerpt="This is an excerpt from the relevant content..."
        )
    ]
    
    response = QueryResponse(
        id="mock-response-id",
        query_id="mock-query-id",
        answer=mock_answer,
        citations=citations,
        sources=["source-1", "source-2"],
        confidence_score=0.85,
        response_time_ms=150
    )
    
    logger.info("Query processed successfully")
    return response


@app.get("/health")
async def health_check():
    """
    Health check endpoint to verify the API and its dependencies are available
    """
    # Check if Cohere client is accessible
    cohere_ok = True
    try:
        # Make a simple request to test the connection
        pass
    except Exception as e:
        logger.error(f"Cohere client health check failed: {e}")
        cohere_ok = False
    
    # Check if Qdrant client is accessible
    qdrant_ok = True
    try:
        # Make a simple request to test the connection
        pass
    except Exception as e:
        logger.error(f"Qdrant client health check failed: {e}")
        qdrant_ok = False
    
    status = "healthy" if cohere_ok and qdrant_ok else "unhealthy"
    
    return {
        "status": status,
        "checks": {
            "cohere_client": {"status": "ok" if cohere_ok else "error"},
            "qdrant_client": {"status": "ok" if qdrant_ok else "error"}
        },
        "timestamp": __import__('datetime').datetime.now().isoformat()
    }


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)